---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
spec:
  selector:
    matchLabels:
               app: test-devops
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
            app: test-devops
    spec:
      containers:
      - name: test-devops
        image: arun4pap/tomcat_webapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
